algoritmo "Talher"
//   Função : Facilitar alimentação
//   Data : 26/09/2023
//   Seção de Declarações
var
  Prato_feito: Caracter
  Quantidade: inteiro
  Peso: Real


inicio
 Prato_feito <- "Surtido"
 Escreval ("Arroz, feijão, bife a cavalo e salada: ", Prato_feito)
 Quantidade <- 3
 Escreval ("Quantidade : ", Quantidade)
 Peso <- 2.5
 Escreval ("Peso/KG: ", Peso)
 fimalgoritmo
